### ISSUE TITLE
[Design] 디자인 피드백 반영

### ISSUE THREAD

**Issue by JunYoung02** [Techeer-H/frontend#140]
**구현 할 기능에 대한 설명**

디자인 피드백 받은 것을 반영합니다.

**TODO List**
- [x]  학생 목록 스크롤 커스텀하기(맥북처럼)
- [x]  폰트 변경하기(맑은 고딕 같은 걸로)
- [x]  성적 등록 작성하기 버튼에서 아이콘보다는 글씨가 직관적일듯
- [x] Header 인지 구별할 수 있도록 글자 크기 키우거나 굵게
- [x] 학생등록 추가 하는 플러스 아이콘 위치 변경
- [x] 강사 부분 평가글이 길어질 때 ... 으로 표시

**참고 자료**
디자인 컨셉과 관련된 추가 정보나 스크린샷 등이 있다면 첨부해 주세요.
