### ISSUE TITLE
[Feature] AI 요약페이지 api를 연결합니다

### ISSUE THREAD

**Issue by JunYoung02** [Techeer-H/frontend#50]
**기능에 대한 설명**

GPT, 학생 성적 그래프, 학생과 부모 평가를 조회합니다

**TODO List**
- [ ] GPT 가져오기 (Read, GET)
- [ ] 학생 성적 그래프 가져오기 (Read, GET)
- [ ] 학생 및 부모 평가 가져오기 (Read, GET)
